version: "3"
services:
  postgres:
    image: postgres:14.5
    container_name: postgres
    environment:
      POSTGRES_DB: simplon-db
      POSTGRES_PASSWORD: simplon
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro
      - pg-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      PGHOST: postgres
      PGDATABASE: simplon-db
      PGPASSWORD: simplon
      PGUSER: postgres
    ports:
      - 3000:3000

volumes:
  pg-data:
